[package]
name = "sample_web_app"
version = "0.1.0"
authors = ["empty <terao@c-style.net>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }
